# apps/api/lfc_api/core/application_constants.py

APPLICATION_TYPE_STAFF = "staff"
APPLICATION_TYPE_VENDOR = "vendor"
APPLICATION_TYPE_PANEL = "panel"

APPLICATION_TYPES = {
    APPLICATION_TYPE_STAFF,
    APPLICATION_TYPE_VENDOR,
    APPLICATION_TYPE_PANEL,
}

APPLICATION_STATUS_DRAFT = "draft"
APPLICATION_STATUS_SUBMITTED = "submitted"
APPLICATION_STATUS_UNDER_REVIEW = "under_review"
APPLICATION_STATUS_APPROVED = "approved"
APPLICATION_STATUS_DECLINED = "declined"
APPLICATION_STATUS_WAITLISTED = "waitlisted"
APPLICATION_STATUS_WITHDRAWN = "withdrawn"

APPLICATION_STATUSES = {
    APPLICATION_STATUS_DRAFT,
    APPLICATION_STATUS_SUBMITTED,
    APPLICATION_STATUS_UNDER_REVIEW,
    APPLICATION_STATUS_APPROVED,
    APPLICATION_STATUS_DECLINED,
    APPLICATION_STATUS_WAITLISTED,
    APPLICATION_STATUS_WITHDRAWN,
}

APPLICATION_STAGE_SUBMITTED = "submitted"
APPLICATION_STAGE_HR_INTERVIEW = "hr_interview"
APPLICATION_STAGE_LEAD_INTERVIEW = "lead_interview"
APPLICATION_STAGE_DIRECTOR_REVIEW = "director_review"
APPLICATION_STAGE_OFFICER_REVIEW = "officer_review"
APPLICATION_STAGE_HR_ONBOARDING = "hr_onboarding"
APPLICATION_STAGE_REVIEW = "review"
APPLICATION_STAGE_COMPLETE = "complete"

APPLICATION_STAGES = {
    APPLICATION_STAGE_SUBMITTED,
    APPLICATION_STAGE_HR_INTERVIEW,
    APPLICATION_STAGE_LEAD_INTERVIEW,
    APPLICATION_STAGE_DIRECTOR_REVIEW,
    APPLICATION_STAGE_OFFICER_REVIEW,
    APPLICATION_STAGE_HR_ONBOARDING,
    APPLICATION_STAGE_REVIEW,
    APPLICATION_STAGE_COMPLETE,
}

TERMINAL_APPLICATION_STATUSES = {
    APPLICATION_STATUS_APPROVED,
    APPLICATION_STATUS_DECLINED,
    APPLICATION_STATUS_WAITLISTED,
    APPLICATION_STATUS_WITHDRAWN,
}


def is_valid_application_type(value: str) -> bool:
    return value in APPLICATION_TYPES


def is_valid_application_status(value: str) -> bool:
    return value in APPLICATION_STATUSES


def is_valid_application_stage(value: str) -> bool:
    return value in APPLICATION_STAGES


def default_stage_for_type(application_type: str, status: str) -> str | None:
    if status == APPLICATION_STATUS_DRAFT:
        return None
    if status == APPLICATION_STATUS_SUBMITTED:
        return APPLICATION_STAGE_SUBMITTED
    return None
